apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world-ns
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007 # You can specify a port in the range 30000-32767, or let Kubernetes choose one.
  type: NodePort
